//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player/playerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""playerInputs"",
    ""maps"": [
        {
            ""name"": ""Controller"",
            ""id"": ""426317b6-682a-4bdd-8271-91663aea50e1"",
            ""actions"": [
                {
                    ""name"": ""UoR"",
                    ""type"": ""Button"",
                    ""id"": ""a704aa73-b75f-4c04-8043-0b685626eed9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoD"",
                    ""type"": ""Button"",
                    ""id"": ""7799eaed-bd45-46c9-901b-89af1a159a36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SoT"",
                    ""type"": ""Button"",
                    ""id"": ""6fb261da-3cae-4792-b356-852ba16985cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CoC"",
                    ""type"": ""Button"",
                    ""id"": ""390efaa6-aca3-4e67-94fd-edf42c4b02fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTs"",
                    ""type"": ""Button"",
                    ""id"": ""478d6a5d-903f-4dcc-a507-460c4f2d364d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTs"",
                    ""type"": ""Button"",
                    ""id"": ""8e2a23e6-b6ad-4fbd-84fb-fffae12974c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f86731cb-a92a-439c-986a-2a3e95b116c0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UoR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e34659e0-1150-4e1c-b534-40d1e80233b3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UoR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79704204-cc99-4299-a66b-f03b9bf45684"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8587778b-505c-47a9-a3cf-ad1778912b23"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""755c3284-02d4-4648-ba1a-5396edee36ce"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SoT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""141463e2-2692-40b7-8bd5-7250e7759e3e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SoT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dce30a63-dae3-4817-9e5a-b30efbcfa841"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79707948-fbde-425e-b782-f485ff478cde"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""668c89a2-a382-45fd-bd8e-d16ead597501"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68c42601-29a8-4082-b78c-920ca8d349e0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bc1da12-9273-496a-b7e8-0c837c921031"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""983cf0e7-7d6d-46d5-b8ad-499bc431c2fb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Controller
        m_Controller = asset.FindActionMap("Controller", throwIfNotFound: true);
        m_Controller_UoR = m_Controller.FindAction("UoR", throwIfNotFound: true);
        m_Controller_LoD = m_Controller.FindAction("LoD", throwIfNotFound: true);
        m_Controller_SoT = m_Controller.FindAction("SoT", throwIfNotFound: true);
        m_Controller_CoC = m_Controller.FindAction("CoC", throwIfNotFound: true);
        m_Controller_LTs = m_Controller.FindAction("LTs", throwIfNotFound: true);
        m_Controller_RTs = m_Controller.FindAction("RTs", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Controller
    private readonly InputActionMap m_Controller;
    private IControllerActions m_ControllerActionsCallbackInterface;
    private readonly InputAction m_Controller_UoR;
    private readonly InputAction m_Controller_LoD;
    private readonly InputAction m_Controller_SoT;
    private readonly InputAction m_Controller_CoC;
    private readonly InputAction m_Controller_LTs;
    private readonly InputAction m_Controller_RTs;
    public struct ControllerActions
    {
        private @PlayerInputs m_Wrapper;
        public ControllerActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @UoR => m_Wrapper.m_Controller_UoR;
        public InputAction @LoD => m_Wrapper.m_Controller_LoD;
        public InputAction @SoT => m_Wrapper.m_Controller_SoT;
        public InputAction @CoC => m_Wrapper.m_Controller_CoC;
        public InputAction @LTs => m_Wrapper.m_Controller_LTs;
        public InputAction @RTs => m_Wrapper.m_Controller_RTs;
        public InputActionMap Get() { return m_Wrapper.m_Controller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControllerActions set) { return set.Get(); }
        public void SetCallbacks(IControllerActions instance)
        {
            if (m_Wrapper.m_ControllerActionsCallbackInterface != null)
            {
                @UoR.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnUoR;
                @UoR.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnUoR;
                @UoR.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnUoR;
                @LoD.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnLoD;
                @LoD.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnLoD;
                @LoD.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnLoD;
                @SoT.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnSoT;
                @SoT.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnSoT;
                @SoT.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnSoT;
                @CoC.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnCoC;
                @CoC.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnCoC;
                @CoC.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnCoC;
                @LTs.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnLTs;
                @LTs.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnLTs;
                @LTs.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnLTs;
                @RTs.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnRTs;
                @RTs.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnRTs;
                @RTs.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnRTs;
            }
            m_Wrapper.m_ControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @UoR.started += instance.OnUoR;
                @UoR.performed += instance.OnUoR;
                @UoR.canceled += instance.OnUoR;
                @LoD.started += instance.OnLoD;
                @LoD.performed += instance.OnLoD;
                @LoD.canceled += instance.OnLoD;
                @SoT.started += instance.OnSoT;
                @SoT.performed += instance.OnSoT;
                @SoT.canceled += instance.OnSoT;
                @CoC.started += instance.OnCoC;
                @CoC.performed += instance.OnCoC;
                @CoC.canceled += instance.OnCoC;
                @LTs.started += instance.OnLTs;
                @LTs.performed += instance.OnLTs;
                @LTs.canceled += instance.OnLTs;
                @RTs.started += instance.OnRTs;
                @RTs.performed += instance.OnRTs;
                @RTs.canceled += instance.OnRTs;
            }
        }
    }
    public ControllerActions @Controller => new ControllerActions(this);
    public interface IControllerActions
    {
        void OnUoR(InputAction.CallbackContext context);
        void OnLoD(InputAction.CallbackContext context);
        void OnSoT(InputAction.CallbackContext context);
        void OnCoC(InputAction.CallbackContext context);
        void OnLTs(InputAction.CallbackContext context);
        void OnRTs(InputAction.CallbackContext context);
    }
}
